### ISSUE TITLE
Does Nebula-Operator supports a way to deploy NebulaGraph Cluster w/ newly introduced CRD?

### ISSUE THREAD

**Issue by ppr1011** [vesoft-inc/nebula-operator#312]
CRD需要开放集群权限，而公司内部往往没有开放这样的集群权限，请问有没有非CRD的安装方式？

**Comment by wey-gu** [comment]
For the current design, unforcedly, no :(.

And this is literaly the first time we heard from one encountering this(restriction on control plane permission on CRD creation), could you try applying for granting that?

Otherwise, you may not be able to leverage the managed K8s in your organization, if that's not easy for you we had to deploy in a non-k8s way or provison a small k3s/minikube for a quick initial evaluation before it's possible to have CRD write permission.

**Comment by ppr1011** [comment]
> For the current design, unforcedly, no :(.
> 
> And this is literaly the first time we heard from one encountering this(restriction on control plane permission on CRD creation), could you try applying for granting that?
> 
> Otherwise, you may not be able to leverage the managed K8s in your organization, if that's not easy for you we had to deploy in a non-k8s way or provison a small k3s/minikube for a quick initial evaluation before it's possible to have CRD write permission.

thx
